### ISSUE TITLE
Error: SPGW-U deps installation failed

### ISSUE THREAD

**Issue by jlchavez10x** [OPENAIRINTERFACE/openair-cn-cups#12]
Hi, 
Please... I'm installing SPGW-U software dependencies. I typed the following line:
$ ~/openair-cn-cups/build/scripts$ ./build_spgwu -I -f

Output is:

CMake Error at CMake/folly-deps.cmake:214 (find_package):
  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:113 (include)

-- Configuring incomplete, errors occurred!
See also "/tmp/folly/_build/CMakeFiles/CMakeOutput.log".
See also "/tmp/folly/_build/CMakeFiles/CMakeError.log".
~/openair-cn/openair-cn-cups/build/scripts
Error: SPGW-U deps installation failed

++++++++++++++++++++++++++++++++++++

OS: Ubuntu Bionic 18.04

**Comment by kpow525** [comment]
I had a similar issue and corrected it by installing the fmt library.
https://fmt.dev/latest/usage.html

**Comment by jlchavez10x** [comment]
Thanks a lot. It worked

**Comment by jrmejiaa** [comment]
@kpow525  Hi, I have the same problem but I could not solve it installing the library. Could you please tell me, what do you do? Maybe I have made something wrong but I don't see it. Thank you
